/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'yukung' at '15/08/10 21:04' with Gradle 2.5
 *
 * @author yukung, @date 15/08/10 21:04
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
