/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'yukung' at '15/08/10 21:04' with Gradle 2.5
 *
 * @author yukung, @date 15/08/10 21:04
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
